### ISSUE TITLE
Beautify document

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/hlsp#4]
Create a module to beautify an AsyncAPI document. So far, we'll only perform one "beautification":

1. Create a list of messages on the root level of the document, using field name `x-parser-messages`. The list should have the following format:

```yaml
x-parser-messages:
  - message: ...
    channel: 'channelName'
```

- [ ] :bug: Unit tests
- [ ] :books: Documentation
